server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/cars/**
        - id: repair-record-service
          uri: lb://repair-record-service
          predicates:
            - Path=/api/repair-records/**
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/api/discounts/**
        - id: repair-service
          uri: lb://repair-service
          predicates:
            - Path=/api/repairs/**
        - id: repair-type-service
          uri: lb://repair-type-service
          predicates:
            - Path=/api/repair-types/**
