server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/cars/**
        - id: repair-record-service
          uri: lb://repair-record-service
          predicates:
            - Path=/api/repair-records/**
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/api/discounts/**
        - id: repair-service
          uri: lb://repair-service
          predicates:
            - Path=/api/repairs/**
        - id: repair-type-service
          uri: lb://repair-type-service
          predicates:
            - Path=/api/repair-types/**
        - id: office-autofix-service
          uri: lb://office-autofix-service
          predicates:
            - Path=/api/office-autofix.service/**
