server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: repair-record-service
          uri: lb://repair-record-service
          predicates:
            - Path=/repair-record/** #ver si esto esta bien
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/discount/**
