server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: car-service
          uri: lb://car-service #es necesario incluir el puerto específico?
          predicates:
            - Path=/api/cars/**
        - id: repair-record-service
          uri: lb://repair-record-service
          predicates:
            - Path=/api/repair-records/**
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/api/discounts/**
        - id: repair-service
          uri: lb://repair-service
          predicates:
            - Path=/api/repairs/**
        #ver para el repairType, y demáses.
