server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://repair-record-service-db:5435/repair-record-service-db
    username: postgres
    password: 1234
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
  instance:
    preferIpAddress: true
