server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://repair-type-service-db:5436/repair-type-service-db
    username: postgres
    password: 1234
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
  instance:
    preferIPAddress: true
